# NOTES:
# cannot have conflicting container names

# COMMANDS:
# docker-compose -p spring-social-green-gang -f docker-compose.yml up -d

version: '3.8'

services:
  #  just a label
  user-service:
    image: user-service
    ports:
      - "8080:8080"
    #    builds app
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    container_name: user-service
    environment:
      # property available provided by spring
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb-user-service
    networks:
      - spring-social

  mongodb-user-service:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/users:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: mongodb-user-service
    restart: unless-stopped
    command: mongod --auth
    networks:
      - spring-social

  mongo-express-user-service:
    image: mongo-express
    ports:
      - "8086:8086"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-user-service
    container_name: mongo-express-user-service
    restart: unless-stopped
    depends_on:
      - mongodb-user-service
    networks:
      - spring-social

networks:
  spring-social:
    driver: bridge
